datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teclan?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

mybatis:
    mapper-locations: classpath:mapper/*.xml


spring.rabbitmq:
    host=127.0.0.1
    port=5672
    username=guest
    password=guest
    publisher-confirms=true
    virtual-host=/