package teclan.springboot.dao;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.type.JdbcType;
import org.mybatis.spring.support.SqlSessionDaoSupport;
import org.springframework.stereotype.Component;
import teclan.springboot.entity.Users1;

import javax.annotation.Resource;

@Component
public interface Users1Mapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users1
     *
     * @mbggenerated Wed Jan 02 16:26:13 CST 2019
     */
    @Delete({
        "delete from users1",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users1
     *
     * @mbggenerated Wed Jan 02 16:26:13 CST 2019
     */
    @Insert({
        "insert into users1 (id, name, ",
        "age)",
        "values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{age,jdbcType=INTEGER})"
    })
    int insert(Users1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users1
     *
     * @mbggenerated Wed Jan 02 16:26:13 CST 2019
     */
    @InsertProvider(type=Users1SqlProvider.class, method="insertSelective")
    int insertSelective(Users1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users1
     *
     * @mbggenerated Wed Jan 02 16:26:13 CST 2019
     */
    @Select({
        "select",
        "id, name, age",
        "from users1",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.INTEGER)
    })
    Users1 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users1
     *
     * @mbggenerated Wed Jan 02 16:26:13 CST 2019
     */
    @UpdateProvider(type=Users1SqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Users1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users1
     *
     * @mbggenerated Wed Jan 02 16:26:13 CST 2019
     */
    @Update({
        "update users1",
        "set name = #{name,jdbcType=VARCHAR},",
          "age = #{age,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Users1 record);

    Users1 findOne(Long id);

}